version: 0.2

phases:
  pre_build:
    commands:
      - echo pre buils started on 'date'...
      - echo loging to docker hub....
      - docker login -u yogita -p kasturi24
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t yogita/ems_java_docker_image:latest .
      - docker tag yogita/ems_java_docker_image:latest yogita/ems_java_docker_image:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push yogita/ems_java_docker_image:latest
